wandb_version: 1

Megan.atom_feature_keys:
  desc: null
  value:
  - is_supernode
  - atomic_num
  - formal_charge
  - chiral_tag
  - num_explicit_hs
  - is_aromatic
Megan.bond_emb_dim:
  desc: null
  value: 32
Megan.bond_feature_keys:
  desc: null
  value:
  - bond_type
  - bond_stereo
Megan.hidden_dim:
  desc: null
  value: 1024
Megan.n_reaction_types:
  desc: null
  value: 10
Megan.reaction_type_emb_dim:
  desc: null
  value: 16
Megan.reaction_type_given:
  desc: null
  value: false
Megan.stateful:
  desc: null
  value: true
MeganDecoder.atom_fc_hidden_dim:
  desc: null
  value: 128
MeganDecoder.bond_atom_dim:
  desc: null
  value: 128
MeganDecoder.bond_fc_hidden_dim:
  desc: null
  value: 128
MeganDecoder.dec_dropout:
  desc: null
  value: 0.3
MeganDecoder.dec_residual:
  desc: null
  value: true
MeganDecoder.n_decoder_conv:
  desc: null
  value: 2
MeganDecoder.n_fc:
  desc: null
  value: 2
MeganEncoder.enc_dropout:
  desc: null
  value: 0.3
MeganEncoder.enc_residual:
  desc: null
  value: true
MeganEncoder.n_encoder_conv:
  desc: null
  value: 4
MultiHeadGraphConvLayer.att_dim:
  desc: null
  value: 128
MultiHeadGraphConvLayer.att_heads:
  desc: null
  value: 8
MultiHeadGraphConvLayer.v2:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    start_time: 1673345537.835005
    t:
      1:
      - 1
      - 3
      - 55
      2:
      - 1
      - 3
      - 55
      3:
      - 5
      - 13
      - 14
      - 16
      - 23
      4: 3.6.10
      5: 0.13.7
      8:
      - 3
      - 5
get_dataset.dataset_key:
  desc: null
  value: uspto_50k
init_wandb.id:
  desc: null
  value: megan1v2
init_wandb.name:
  desc: null
  value: v2
init_wandb.project:
  desc: null
  value: megan
train_megan.batch_size:
  desc: null
  value: 3
train_megan.early_stopping:
  desc: null
  value: 16
train_megan.featurizer_key:
  desc: null
  value: megan_16_bfs_randat
train_megan.gen_lr_factor:
  desc: null
  value: 0.05
train_megan.gen_lr_patience:
  desc: null
  value: 6
train_megan.learning_rate:
  desc: null
  value: 0.0001
train_megan.max_n_epochs:
  desc: null
  value: 200
train_megan.megan_warmup_epochs:
  desc: null
  value: 1
train_megan.start_epoch:
  desc: null
  value: 0
train_megan.train_samples_per_epoch:
  desc: null
  value: 20000
train_megan.valid_samples_per_epoch:
  desc: null
  value: 5000
